const mongoose = require("mongoose");
const coffeeMemberSchema = new mongoose.Schema({
  subscription_id: Number,
  subscription_cancelled_on: String,
  subscription_created_on: String,
  subscription_updated_on: String,
  subscription_current_period_start: String,
  subscription_current_period_end: String,
  subscription_coffee_price: String,
  subscription_coffee_num: Number,
  subscription_is_cancelled: Number,
  subscription_is_cancelled_at_period_end: Number,
  subscription_currency: String,
  subscription_message: String,
  message_visibility: Number,
  subscription_duration_type: String,
  referer: String,
  country: String,
  is_razorpay: Number,
  subscription_hidden: Number,
  membership_level_id: Number,
  is_manual_payout: Number,
  is_paused: Number,
  stripe_status: String,
  transaction_id: String,
  payer_email: String,
  payer_name: String,
  isNoUpdated: Boolean,
});
module.exports = mongoose.model("coffees-member", coffeeMemberSchema);
